#!/bin/bash
cat > ./dist/cjs/package.json <<!EOF
{
    "type": "commonjs"
}
!EOF

cat > ./dist/esm/package.json <<!EOF
{
    "type": "module"
}
!EOF

echo "Do Not make any modifications to files under the dist directory. They are generated by the build process." > ./dist/Readme.md
